[package]
name        = "genetikus-magma"
version     = { workspace = true }
edition     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }
rust-version = { workspace = true }
description = "Lava-inspired Process / Port / Channel abstractions for genetikus."

[dependencies]
crossbeam-channel = { workspace = true }
thiserror         = { workspace = true }
